# Project setup:
Rails:
  Enabled: true
AllCops:
  Include:
    - '**/*.rb'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - Gemfile
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

# Cop configuration:

# Bundler

# Gemspec

# Layout
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/AlignArray:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/ElseAlignment:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false
Layout/SpaceInsideRangeLiteral:
  Enabled: false

# Lint
Lint/HandleExceptions:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Naming
Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
# disabled until class vaiables in extras become constants
Naming/UncommunicativeMethodParamName:
  Enabled: false
Naming/VariableName:
  Enabled: false

# Performance
Performance/Casecmp:
  Enabled: false
Performance/RedundantMatch:
  Enabled: false

# Rails
Rails/FilePath:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false

# Security

# Style
Style/AndOr:
  EnforcedStyle: conditionals
Style/BlockDelimiters:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
# It would be nice to have this on, but I'm not up for writing 66 of these in
# the process of addressing the initial 4,489 cop warnings.
Style/Documentation:
  Enabled: false
  Exclude: [db/migrate/**/*, spec/**/*, test/**/*]
Style/DoubleNegation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
Style/IfInsideElse:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/NegatedIf:
  EnforcedStyle: postfix
Style/NumericPredicate:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/RegexpLiteral:
  AllowInnerSlashes: true
