# Project setup:
Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

# Layout
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Lint
Lint/HandleExceptions:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Naming
Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
Naming/PredicateName:
  Enabled: false

# Rails
Rails/FilePath:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false

# Style
Style/CollectionMethods:
  Enabled: true
# It would be nice to have this on, but I'm not up for writing 66 of these in
# the process of addressing the initial 4,489 cop warnings.
Style/Documentation:
  Enabled: false
  Exclude: [db/migrate/**/*, spec/**/*, test/**/*]
Style/DoubleNegation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/Send:
  Enabled: true
Style/StringMethods:
  Enabled: true
Style/SymbolArray:
  Enabled: true
