---
language: ruby
services:
  - postgres

env:
  global:
    - DATABASE_HOST=localhost
    - DATABASE_USER=postgres
    - RAILS_ENV=test

before_script:
  - ./bin/rails db:create
  - ./bin/rails db:schema:load

script:
  - bundle exec rubocop
  - bundle exec rspec
