# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain: example.com
  name: Lobsters
  read_only?: false
  secret_key_base: f6249dff01c3dd76b3f36a6c6a1e35b4e25b205f0f435c22fbe70a4d17d78205cd9a4dced92a5092b1e7e69a8334852462cc23c2a825b1611dec516b6afdd10e

test:
  domain: example.com
  name: Lobsters
  read_only?: false
  secret_key_base: 0ea31f9c376f604823c7e08d39aefcf41f9f1217df083cc45afb8c969a1b279a213119c7fba850be51ef4343bc7207000702c431e3e1aec53e3fa0152062c7ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  allow_invitation_requests?: <%= ENV["ALLOW_INVITATION_REQUESTS"] == "true" %>
  diffbot_api_key: <%= ENV["DIFFBOT_API_KEY"] %>
  domain: <%= ENV["DOMAIN"] %>
  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  mailgun_api_key: <%= ENV["MAILGUN_API_KEY"] %>
  mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %>
  name: <%= ENV["NAME"] %>
  open_signups?: <%= ENV["OPEN_SIGNUPS"] == "true" %>
  pushover_api_token: <%= ENV["PUSHOVER_API_TOKEN"] %>
  pushover_subscription_code: <%= ENV["PUSHOVER_SUBSCRIPTION_CODE"] %>
  read_only?: <%= ENV["READ_ONLY"] == "true" %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack_webhook_url: <%= ENV["SLACK_WEBHOOK_URL"] %>
  twitter_auth_secret: <%= ENV["TWITTER_AUTH_SECRET"] %>
  twitter_auth_token: <%= ENV["TWITTER_AUTH_TOKEN"] %>
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  twitter_username: <%= ENV["TWITTER_USERNAME"] %>
